# Generated by Django 4.0.3 on 2022-04-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='caso',
            fields=[
                ('id_caso', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=20)),
                ('cantidad_demandas', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'caso',
                'verbose_name_plural': 'casos',
            },
        ),
        migrations.CreateModel(
            name='demanda',
            fields=[
                ('id_demanda', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=20)),
                ('nombre_tipo', models.CharField(max_length=200)),
                ('Descripcion', models.CharField(default='', max_length=1000)),
                ('rut', models.CharField(default='', max_length=10)),
                ('nombre', models.CharField(default='', max_length=50)),
                ('apellido', models.CharField(default='', max_length=50)),
                ('telefono', models.CharField(default='', max_length=12)),
                ('comuna', models.CharField(default='', max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('rutdemando', models.CharField(default='', max_length=10)),
                ('nombredemando', models.CharField(default='', max_length=50)),
                ('apellidodemando', models.CharField(default='', max_length=50)),
                ('telefonodemando', models.CharField(default='', max_length=12)),
                ('comunademando', models.CharField(default='', max_length=50)),
                ('regiondemando', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'demanda',
                'verbose_name_plural': 'demandas',
            },
        ),
        migrations.CreateModel(
            name='informe2',
            fields=[
                ('id_informe', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'informe2',
                'verbose_name_plural': 'informes2',
            },
        ),
        migrations.CreateModel(
            name='nombre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
